features:
  majority_window: 15
  technical_indicators: 
   
  feature_selection:
    discrete_features: 
      - K0
      - K1 
      - K3
      - K4
      - K5
      - K6
      - K7
      - K8
      - K9
      - K10
      - K11
      - K12
      - K13
      - K14
      - K15
      - K17
      - K18
      - K19
      - K20
      - K21
      - K22
      - K23
      - K24
      - K25
    
      
    
    real_features: 
      - open
      - BBM_20_1.5
      - MACD
      - MACD_s
      - ma_5
      - ma_30
      - hs300_volume_std
      - zz2000_volume_std
      - relative_volume_std
      - hs300_return_std
      - zz2000_return_std
      - relative_return_std
      - Finance
      - momentum_5
      
   
     