main_folder: "D:/lstm_model/lstm"

directories:
  model_dir: "{main_folder}/models"
  plots_dir: "{main_folder}/plots"
  predictions_dir: "{main_folder}/prediction"
  feature_weights_dir: "{main_folder}/feature_weights"
  

files:
  scaler_path: "{main_folder}/models/scaler.pkl"
  model_path: "{main_folder}/models/xgb_best_model_cls.pkl"
  all_pred_path: "{main_folder}/prediction/predictions_all.csv"
  test_pred_path: "{main_folder}/prediction/test_predictions.csv"
  acc_plot_path: "{main_folder}/plots/train_val_accuracy_curve.png"
  backtesting_path: "{main_folder}/backtesting"
 
signals:
  current_signal: "model1" #回测文件夹命名

data:
  
  raw_data_path: "D:/lstm_model/data/raw_signal_data/*.csv"
  combine_path: "D:/lstm_model/data/combine/*.csv"
  index_return_path: "D:/OneDrive/Data_prepared_test/data_timeSeries/index_return.csv"
  chinese_valuation_date_path: "D:/OneDrive/Data_prepared_test/data_other/chinese_valuation_date.xlsx"
  output_path: "D:/lstm_model/output"


